// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package oldmain

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"migration/pkg/model"
)

func newWinCodeRecordsVipTmp(db *gorm.DB, opts ...gen.DOOption) winCodeRecordsVipTmp {
	_winCodeRecordsVipTmp := winCodeRecordsVipTmp{}

	_winCodeRecordsVipTmp.winCodeRecordsVipTmpDo.UseDB(db, opts...)
	_winCodeRecordsVipTmp.winCodeRecordsVipTmpDo.UseModel(&model.WinCodeRecordsVipTmp{})

	tableName := _winCodeRecordsVipTmp.winCodeRecordsVipTmpDo.TableName()
	_winCodeRecordsVipTmp.ALL = field.NewAsterisk(tableName)
	_winCodeRecordsVipTmp.ID = field.NewInt64(tableName, "id")
	_winCodeRecordsVipTmp.Remark = field.NewString(tableName, "remark")
	_winCodeRecordsVipTmp.UID = field.NewInt32(tableName, "uid")
	_winCodeRecordsVipTmp.ValidAmount = field.NewFloat64(tableName, "valid_amount")
	_winCodeRecordsVipTmp.Category = field.NewInt32(tableName, "category")
	_winCodeRecordsVipTmp.Version = field.NewInt32(tableName, "version")
	_winCodeRecordsVipTmp.CreatedAt = field.NewInt32(tableName, "created_at")
	_winCodeRecordsVipTmp.UpdatedAt = field.NewInt32(tableName, "updated_at")
	_winCodeRecordsVipTmp.UpdatedUser = field.NewString(tableName, "updated_user")

	_winCodeRecordsVipTmp.fillFieldMap()

	return _winCodeRecordsVipTmp
}

// winCodeRecordsVipTmp VIP会员有效流水表
type winCodeRecordsVipTmp struct {
	winCodeRecordsVipTmpDo

	ALL         field.Asterisk
	ID          field.Int64   // 自增主键
	Remark      field.String  // 备注
	UID         field.Int32   // UID
	ValidAmount field.Float64 // 有效投注额/赠送金额
	Category    field.Int32   // 类型:1-有效投注额 2-赠送金额
	Version     field.Int32   // 更新版本号
	CreatedAt   field.Int32   // 创建时间
	UpdatedAt   field.Int32   // 修改时间
	UpdatedUser field.String  // 最后修改人

	fieldMap map[string]field.Expr
}

func (w winCodeRecordsVipTmp) Table(newTableName string) *winCodeRecordsVipTmp {
	w.winCodeRecordsVipTmpDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w winCodeRecordsVipTmp) As(alias string) *winCodeRecordsVipTmp {
	w.winCodeRecordsVipTmpDo.DO = *(w.winCodeRecordsVipTmpDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *winCodeRecordsVipTmp) updateTableName(table string) *winCodeRecordsVipTmp {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.Remark = field.NewString(table, "remark")
	w.UID = field.NewInt32(table, "uid")
	w.ValidAmount = field.NewFloat64(table, "valid_amount")
	w.Category = field.NewInt32(table, "category")
	w.Version = field.NewInt32(table, "version")
	w.CreatedAt = field.NewInt32(table, "created_at")
	w.UpdatedAt = field.NewInt32(table, "updated_at")
	w.UpdatedUser = field.NewString(table, "updated_user")

	w.fillFieldMap()

	return w
}

func (w *winCodeRecordsVipTmp) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *winCodeRecordsVipTmp) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 9)
	w.fieldMap["id"] = w.ID
	w.fieldMap["remark"] = w.Remark
	w.fieldMap["uid"] = w.UID
	w.fieldMap["valid_amount"] = w.ValidAmount
	w.fieldMap["category"] = w.Category
	w.fieldMap["version"] = w.Version
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["updated_user"] = w.UpdatedUser
}

func (w winCodeRecordsVipTmp) clone(db *gorm.DB) winCodeRecordsVipTmp {
	w.winCodeRecordsVipTmpDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w winCodeRecordsVipTmp) replaceDB(db *gorm.DB) winCodeRecordsVipTmp {
	w.winCodeRecordsVipTmpDo.ReplaceDB(db)
	return w
}

type winCodeRecordsVipTmpDo struct{ gen.DO }

func (w winCodeRecordsVipTmpDo) Debug() *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Debug())
}

func (w winCodeRecordsVipTmpDo) WithContext(ctx context.Context) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w winCodeRecordsVipTmpDo) ReadDB() *winCodeRecordsVipTmpDo {
	return w.Clauses(dbresolver.Read)
}

func (w winCodeRecordsVipTmpDo) WriteDB() *winCodeRecordsVipTmpDo {
	return w.Clauses(dbresolver.Write)
}

func (w winCodeRecordsVipTmpDo) Session(config *gorm.Session) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Session(config))
}

func (w winCodeRecordsVipTmpDo) Clauses(conds ...clause.Expression) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w winCodeRecordsVipTmpDo) Returning(value interface{}, columns ...string) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w winCodeRecordsVipTmpDo) Not(conds ...gen.Condition) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w winCodeRecordsVipTmpDo) Or(conds ...gen.Condition) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w winCodeRecordsVipTmpDo) Select(conds ...field.Expr) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w winCodeRecordsVipTmpDo) Where(conds ...gen.Condition) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w winCodeRecordsVipTmpDo) Order(conds ...field.Expr) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w winCodeRecordsVipTmpDo) Distinct(cols ...field.Expr) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w winCodeRecordsVipTmpDo) Omit(cols ...field.Expr) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w winCodeRecordsVipTmpDo) Join(table schema.Tabler, on ...field.Expr) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w winCodeRecordsVipTmpDo) LeftJoin(table schema.Tabler, on ...field.Expr) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w winCodeRecordsVipTmpDo) RightJoin(table schema.Tabler, on ...field.Expr) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w winCodeRecordsVipTmpDo) Group(cols ...field.Expr) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w winCodeRecordsVipTmpDo) Having(conds ...gen.Condition) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w winCodeRecordsVipTmpDo) Limit(limit int) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w winCodeRecordsVipTmpDo) Offset(offset int) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w winCodeRecordsVipTmpDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w winCodeRecordsVipTmpDo) Unscoped() *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Unscoped())
}

func (w winCodeRecordsVipTmpDo) Create(values ...*model.WinCodeRecordsVipTmp) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w winCodeRecordsVipTmpDo) CreateInBatches(values []*model.WinCodeRecordsVipTmp, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w winCodeRecordsVipTmpDo) Save(values ...*model.WinCodeRecordsVipTmp) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w winCodeRecordsVipTmpDo) First() (*model.WinCodeRecordsVipTmp, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinCodeRecordsVipTmp), nil
	}
}

func (w winCodeRecordsVipTmpDo) Take() (*model.WinCodeRecordsVipTmp, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinCodeRecordsVipTmp), nil
	}
}

func (w winCodeRecordsVipTmpDo) Last() (*model.WinCodeRecordsVipTmp, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinCodeRecordsVipTmp), nil
	}
}

func (w winCodeRecordsVipTmpDo) Find() ([]*model.WinCodeRecordsVipTmp, error) {
	result, err := w.DO.Find()
	return result.([]*model.WinCodeRecordsVipTmp), err
}

func (w winCodeRecordsVipTmpDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinCodeRecordsVipTmp, err error) {
	buf := make([]*model.WinCodeRecordsVipTmp, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w winCodeRecordsVipTmpDo) FindInBatches(result *[]*model.WinCodeRecordsVipTmp, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w winCodeRecordsVipTmpDo) Attrs(attrs ...field.AssignExpr) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w winCodeRecordsVipTmpDo) Assign(attrs ...field.AssignExpr) *winCodeRecordsVipTmpDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w winCodeRecordsVipTmpDo) Joins(fields ...field.RelationField) *winCodeRecordsVipTmpDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w winCodeRecordsVipTmpDo) Preload(fields ...field.RelationField) *winCodeRecordsVipTmpDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w winCodeRecordsVipTmpDo) FirstOrInit() (*model.WinCodeRecordsVipTmp, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinCodeRecordsVipTmp), nil
	}
}

func (w winCodeRecordsVipTmpDo) FirstOrCreate() (*model.WinCodeRecordsVipTmp, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinCodeRecordsVipTmp), nil
	}
}

func (w winCodeRecordsVipTmpDo) FindByPage(offset int, limit int) (result []*model.WinCodeRecordsVipTmp, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w winCodeRecordsVipTmpDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w winCodeRecordsVipTmpDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w winCodeRecordsVipTmpDo) Delete(models ...*model.WinCodeRecordsVipTmp) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *winCodeRecordsVipTmpDo) withDO(do gen.Dao) *winCodeRecordsVipTmpDo {
	w.DO = *do.(*gen.DO)
	return w
}
