// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package oldmain

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"migration/pkg/model"
)

func newWinAgentCommissionRate(db *gorm.DB, opts ...gen.DOOption) winAgentCommissionRate {
	_winAgentCommissionRate := winAgentCommissionRate{}

	_winAgentCommissionRate.winAgentCommissionRateDo.UseDB(db, opts...)
	_winAgentCommissionRate.winAgentCommissionRateDo.UseModel(&model.WinAgentCommissionRate{})

	tableName := _winAgentCommissionRate.winAgentCommissionRateDo.TableName()
	_winAgentCommissionRate.ALL = field.NewAsterisk(tableName)
	_winAgentCommissionRate.AgentLevel = field.NewInt32(tableName, "agent_level")
	_winAgentCommissionRate.AgentLevelRate = field.NewFloat64(tableName, "agent_level_rate")
	_winAgentCommissionRate.CreatedAt = field.NewInt32(tableName, "created_at")
	_winAgentCommissionRate.UpdatedAt = field.NewInt32(tableName, "updated_at")

	_winAgentCommissionRate.fillFieldMap()

	return _winAgentCommissionRate
}

// winAgentCommissionRate 代理佣金分成比例表
type winAgentCommissionRate struct {
	winAgentCommissionRateDo

	ALL            field.Asterisk
	AgentLevel     field.Int32   // 代理层级
	AgentLevelRate field.Float64 // 佣金比例
	CreatedAt      field.Int32
	UpdatedAt      field.Int32

	fieldMap map[string]field.Expr
}

func (w winAgentCommissionRate) Table(newTableName string) *winAgentCommissionRate {
	w.winAgentCommissionRateDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w winAgentCommissionRate) As(alias string) *winAgentCommissionRate {
	w.winAgentCommissionRateDo.DO = *(w.winAgentCommissionRateDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *winAgentCommissionRate) updateTableName(table string) *winAgentCommissionRate {
	w.ALL = field.NewAsterisk(table)
	w.AgentLevel = field.NewInt32(table, "agent_level")
	w.AgentLevelRate = field.NewFloat64(table, "agent_level_rate")
	w.CreatedAt = field.NewInt32(table, "created_at")
	w.UpdatedAt = field.NewInt32(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *winAgentCommissionRate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *winAgentCommissionRate) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 4)
	w.fieldMap["agent_level"] = w.AgentLevel
	w.fieldMap["agent_level_rate"] = w.AgentLevelRate
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w winAgentCommissionRate) clone(db *gorm.DB) winAgentCommissionRate {
	w.winAgentCommissionRateDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w winAgentCommissionRate) replaceDB(db *gorm.DB) winAgentCommissionRate {
	w.winAgentCommissionRateDo.ReplaceDB(db)
	return w
}

type winAgentCommissionRateDo struct{ gen.DO }

func (w winAgentCommissionRateDo) Debug() *winAgentCommissionRateDo {
	return w.withDO(w.DO.Debug())
}

func (w winAgentCommissionRateDo) WithContext(ctx context.Context) *winAgentCommissionRateDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w winAgentCommissionRateDo) ReadDB() *winAgentCommissionRateDo {
	return w.Clauses(dbresolver.Read)
}

func (w winAgentCommissionRateDo) WriteDB() *winAgentCommissionRateDo {
	return w.Clauses(dbresolver.Write)
}

func (w winAgentCommissionRateDo) Session(config *gorm.Session) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Session(config))
}

func (w winAgentCommissionRateDo) Clauses(conds ...clause.Expression) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w winAgentCommissionRateDo) Returning(value interface{}, columns ...string) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w winAgentCommissionRateDo) Not(conds ...gen.Condition) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w winAgentCommissionRateDo) Or(conds ...gen.Condition) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w winAgentCommissionRateDo) Select(conds ...field.Expr) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w winAgentCommissionRateDo) Where(conds ...gen.Condition) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w winAgentCommissionRateDo) Order(conds ...field.Expr) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w winAgentCommissionRateDo) Distinct(cols ...field.Expr) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w winAgentCommissionRateDo) Omit(cols ...field.Expr) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w winAgentCommissionRateDo) Join(table schema.Tabler, on ...field.Expr) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w winAgentCommissionRateDo) LeftJoin(table schema.Tabler, on ...field.Expr) *winAgentCommissionRateDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w winAgentCommissionRateDo) RightJoin(table schema.Tabler, on ...field.Expr) *winAgentCommissionRateDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w winAgentCommissionRateDo) Group(cols ...field.Expr) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w winAgentCommissionRateDo) Having(conds ...gen.Condition) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w winAgentCommissionRateDo) Limit(limit int) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w winAgentCommissionRateDo) Offset(offset int) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w winAgentCommissionRateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w winAgentCommissionRateDo) Unscoped() *winAgentCommissionRateDo {
	return w.withDO(w.DO.Unscoped())
}

func (w winAgentCommissionRateDo) Create(values ...*model.WinAgentCommissionRate) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w winAgentCommissionRateDo) CreateInBatches(values []*model.WinAgentCommissionRate, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w winAgentCommissionRateDo) Save(values ...*model.WinAgentCommissionRate) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w winAgentCommissionRateDo) First() (*model.WinAgentCommissionRate, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinAgentCommissionRate), nil
	}
}

func (w winAgentCommissionRateDo) Take() (*model.WinAgentCommissionRate, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinAgentCommissionRate), nil
	}
}

func (w winAgentCommissionRateDo) Last() (*model.WinAgentCommissionRate, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinAgentCommissionRate), nil
	}
}

func (w winAgentCommissionRateDo) Find() ([]*model.WinAgentCommissionRate, error) {
	result, err := w.DO.Find()
	return result.([]*model.WinAgentCommissionRate), err
}

func (w winAgentCommissionRateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinAgentCommissionRate, err error) {
	buf := make([]*model.WinAgentCommissionRate, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w winAgentCommissionRateDo) FindInBatches(result *[]*model.WinAgentCommissionRate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w winAgentCommissionRateDo) Attrs(attrs ...field.AssignExpr) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w winAgentCommissionRateDo) Assign(attrs ...field.AssignExpr) *winAgentCommissionRateDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w winAgentCommissionRateDo) Joins(fields ...field.RelationField) *winAgentCommissionRateDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w winAgentCommissionRateDo) Preload(fields ...field.RelationField) *winAgentCommissionRateDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w winAgentCommissionRateDo) FirstOrInit() (*model.WinAgentCommissionRate, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinAgentCommissionRate), nil
	}
}

func (w winAgentCommissionRateDo) FirstOrCreate() (*model.WinAgentCommissionRate, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinAgentCommissionRate), nil
	}
}

func (w winAgentCommissionRateDo) FindByPage(offset int, limit int) (result []*model.WinAgentCommissionRate, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w winAgentCommissionRateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w winAgentCommissionRateDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w winAgentCommissionRateDo) Delete(models ...*model.WinAgentCommissionRate) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *winAgentCommissionRateDo) withDO(do gen.Dao) *winAgentCommissionRateDo {
	w.DO = *do.(*gen.DO)
	return w
}
