// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package oldmain

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"migration/pkg/model"
)

func newWinMerchant(db *gorm.DB, opts ...gen.DOOption) winMerchant {
	_winMerchant := winMerchant{}

	_winMerchant.winMerchantDo.UseDB(db, opts...)
	_winMerchant.winMerchantDo.UseModel(&model.WinMerchant{})

	tableName := _winMerchant.winMerchantDo.TableName()
	_winMerchant.ALL = field.NewAsterisk(tableName)
	_winMerchant.ID = field.NewInt32(tableName, "id")
	_winMerchant.Name = field.NewString(tableName, "name")
	_winMerchant.Category = field.NewInt32(tableName, "category")
	_winMerchant.PromoteCode = field.NewString(tableName, "promote_code")
	_winMerchant.Address = field.NewString(tableName, "address")

	_winMerchant.fillFieldMap()

	return _winMerchant
}

// winMerchant 商户信息
type winMerchant struct {
	winMerchantDo

	ALL         field.Asterisk
	ID          field.Int32
	Name        field.String // 商户名称
	Category    field.Int32  // 商户类型 1线下门店 2线上
	PromoteCode field.String // 推广码
	Address     field.String // 商户地址

	fieldMap map[string]field.Expr
}

func (w winMerchant) Table(newTableName string) *winMerchant {
	w.winMerchantDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w winMerchant) As(alias string) *winMerchant {
	w.winMerchantDo.DO = *(w.winMerchantDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *winMerchant) updateTableName(table string) *winMerchant {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt32(table, "id")
	w.Name = field.NewString(table, "name")
	w.Category = field.NewInt32(table, "category")
	w.PromoteCode = field.NewString(table, "promote_code")
	w.Address = field.NewString(table, "address")

	w.fillFieldMap()

	return w
}

func (w *winMerchant) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *winMerchant) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 5)
	w.fieldMap["id"] = w.ID
	w.fieldMap["name"] = w.Name
	w.fieldMap["category"] = w.Category
	w.fieldMap["promote_code"] = w.PromoteCode
	w.fieldMap["address"] = w.Address
}

func (w winMerchant) clone(db *gorm.DB) winMerchant {
	w.winMerchantDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w winMerchant) replaceDB(db *gorm.DB) winMerchant {
	w.winMerchantDo.ReplaceDB(db)
	return w
}

type winMerchantDo struct{ gen.DO }

func (w winMerchantDo) Debug() *winMerchantDo {
	return w.withDO(w.DO.Debug())
}

func (w winMerchantDo) WithContext(ctx context.Context) *winMerchantDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w winMerchantDo) ReadDB() *winMerchantDo {
	return w.Clauses(dbresolver.Read)
}

func (w winMerchantDo) WriteDB() *winMerchantDo {
	return w.Clauses(dbresolver.Write)
}

func (w winMerchantDo) Session(config *gorm.Session) *winMerchantDo {
	return w.withDO(w.DO.Session(config))
}

func (w winMerchantDo) Clauses(conds ...clause.Expression) *winMerchantDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w winMerchantDo) Returning(value interface{}, columns ...string) *winMerchantDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w winMerchantDo) Not(conds ...gen.Condition) *winMerchantDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w winMerchantDo) Or(conds ...gen.Condition) *winMerchantDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w winMerchantDo) Select(conds ...field.Expr) *winMerchantDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w winMerchantDo) Where(conds ...gen.Condition) *winMerchantDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w winMerchantDo) Order(conds ...field.Expr) *winMerchantDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w winMerchantDo) Distinct(cols ...field.Expr) *winMerchantDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w winMerchantDo) Omit(cols ...field.Expr) *winMerchantDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w winMerchantDo) Join(table schema.Tabler, on ...field.Expr) *winMerchantDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w winMerchantDo) LeftJoin(table schema.Tabler, on ...field.Expr) *winMerchantDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w winMerchantDo) RightJoin(table schema.Tabler, on ...field.Expr) *winMerchantDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w winMerchantDo) Group(cols ...field.Expr) *winMerchantDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w winMerchantDo) Having(conds ...gen.Condition) *winMerchantDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w winMerchantDo) Limit(limit int) *winMerchantDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w winMerchantDo) Offset(offset int) *winMerchantDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w winMerchantDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *winMerchantDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w winMerchantDo) Unscoped() *winMerchantDo {
	return w.withDO(w.DO.Unscoped())
}

func (w winMerchantDo) Create(values ...*model.WinMerchant) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w winMerchantDo) CreateInBatches(values []*model.WinMerchant, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w winMerchantDo) Save(values ...*model.WinMerchant) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w winMerchantDo) First() (*model.WinMerchant, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinMerchant), nil
	}
}

func (w winMerchantDo) Take() (*model.WinMerchant, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinMerchant), nil
	}
}

func (w winMerchantDo) Last() (*model.WinMerchant, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinMerchant), nil
	}
}

func (w winMerchantDo) Find() ([]*model.WinMerchant, error) {
	result, err := w.DO.Find()
	return result.([]*model.WinMerchant), err
}

func (w winMerchantDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WinMerchant, err error) {
	buf := make([]*model.WinMerchant, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w winMerchantDo) FindInBatches(result *[]*model.WinMerchant, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w winMerchantDo) Attrs(attrs ...field.AssignExpr) *winMerchantDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w winMerchantDo) Assign(attrs ...field.AssignExpr) *winMerchantDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w winMerchantDo) Joins(fields ...field.RelationField) *winMerchantDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w winMerchantDo) Preload(fields ...field.RelationField) *winMerchantDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w winMerchantDo) FirstOrInit() (*model.WinMerchant, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinMerchant), nil
	}
}

func (w winMerchantDo) FirstOrCreate() (*model.WinMerchant, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WinMerchant), nil
	}
}

func (w winMerchantDo) FindByPage(offset int, limit int) (result []*model.WinMerchant, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w winMerchantDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w winMerchantDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w winMerchantDo) Delete(models ...*model.WinMerchant) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *winMerchantDo) withDO(do gen.Dao) *winMerchantDo {
	w.DO = *do.(*gen.DO)
	return w
}
