// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActivityAlertUserConfig = "activity_alert_user_config"

// ActivityAlertUserConfig 告警不再提示配置表
type ActivityAlertUserConfig struct {
	ID         int64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`               // 主键
	ActivityID int64 `gorm:"column:activity_id;not null;comment:活动id" json:"activity_id"`                // 活动id
	AlarmType  int32 `gorm:"column:alarm_type;not null;comment:告警类型：1今日超发告警，2总预算超发告警" json:"alarm_type"` // 告警类型：1今日超发告警，2总预算超发告警
	UserID     int64 `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                        // 用户ID
	CreatedAt  int64 `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                  // 创建时间
}

// TableName ActivityAlertUserConfig's table name
func (*ActivityAlertUserConfig) TableName() string {
	return TableNameActivityAlertUserConfig
}
