// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActivityChristmasWarningThreshold = "activity_christmas_warning_threshold"

// ActivityChristmasWarningThreshold 圣诞节阈值预警表
type ActivityChristmasWarningThreshold struct {
	ID                    int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                                           // 自增主键
	WarningStatus         int32   `gorm:"column:warning_status;not null;comment:预警状态：1-预警开启，0-预警关闭" json:"warning_status"`                          // 预警状态：1-预警开启，0-预警关闭
	DailyJackpotThreshold float64 `gorm:"column:daily_jackpot_threshold;not null;default:0.0000;comment:单日彩金上限告警阈值" json:"daily_jackpot_threshold"` // 单日彩金上限告警阈值
	TotalBudgetThreshold  float64 `gorm:"column:total_budget_threshold;not null;default:0.0000;comment:活动总预算告警阈值" json:"total_budget_threshold"`    // 活动总预算告警阈值
	CreateAt              int32   `gorm:"column:create_at;not null;comment:创建时间" json:"create_at"`                                                  // 创建时间
	UpdateAt              int32   `gorm:"column:update_at;not null;comment:修改时间" json:"update_at"`                                                  // 修改时间
	OpUser                string  `gorm:"column:op_user;not null;default:system;comment:操作人" json:"op_user"`                                        // 操作人
}

// TableName ActivityChristmasWarningThreshold's table name
func (*ActivityChristmasWarningThreshold) TableName() string {
	return TableNameActivityChristmasWarningThreshold
}
