// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAgentCommissionRate = "agent_commission_rate"

// AgentCommissionRate 代理佣金分成比例表V2
type AgentCommissionRate struct {
	ID          int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`           // id
	AgentID     int32   `gorm:"column:agent_id;not null;comment:代理uid" json:"agent_id"`                 // 代理uid
	SettingType int32   `gorm:"column:setting_type;not null;comment:0總代,1非總代" json:"setting_type"`      // 0總代,1非總代
	MinAmount   int64   `gorm:"column:min_amount;not null;comment:金额区间 小" json:"min_amount"`            // 金额区间 小
	MaxAmount   int64   `gorm:"column:max_amount;not null;comment:金额区间 大" json:"max_amount"`            // 金额区间 大
	AgentRate   float64 `gorm:"column:agent_rate;not null;default:0.00;comment:佣金比例" json:"agent_rate"` // 佣金比例
	CreatedAt   int32   `gorm:"column:created_at;not null;comment:創建時間" json:"created_at"`              // 創建時間
	UpdatedAt   int32   `gorm:"column:updated_at;not null;comment:更新時間" json:"updated_at"`              // 更新時間
}

// TableName AgentCommissionRate's table name
func (*AgentCommissionRate) TableName() string {
	return TableNameAgentCommissionRate
}
