// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChristmasNewUserSupportRule = "christmas_new_user_support_rules"

// ChristmasNewUserSupportRule 圣诞活动新用户一次助力规则表
type ChristmasNewUserSupportRule struct {
	ID                            int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                                                                       // 自增主键
	RuleID                        int64   `gorm:"column:rule_id;not null;comment:规则ID" json:"rule_id"`                                                                                  // 规则ID
	ActivityID                    int64   `gorm:"column:activity_id;not null;comment:活动ID" json:"activity_id"`                                                                          // 活动ID
	NewOneSupportSuccessRangeFrom float64 `gorm:"column:new_one_support_success_range_from;not null;default:0.0000;comment:新用户一次助力成功充值金额范围起" json:"new_one_support_success_range_from"` // 新用户一次助力成功充值金额范围起
	NewOneSupportSuccessRangeTo   float64 `gorm:"column:new_one_support_success_range_to;not null;default:0.0000;comment:新用户一次助力成功充值金额范围止" json:"new_one_support_success_range_to"`     // 新用户一次助力成功充值金额范围止
	NewOneSupportSuccessPr        float64 `gorm:"column:new_one_support_success_pr;not null;default:0.0000;comment:新用户一次助力成功比例" json:"new_one_support_success_pr"`                      // 新用户一次助力成功比例
	CreateAt                      int32   `gorm:"column:create_at;not null;comment:创建时间" json:"create_at"`                                                                              // 创建时间
	UpdateAt                      int32   `gorm:"column:update_at;not null;comment:修改时间" json:"update_at"`                                                                              // 修改时间
	OpUser                        string  `gorm:"column:op_user;not null;default:system;comment:操作人" json:"op_user"`                                                                    // 操作人
}

// TableName ChristmasNewUserSupportRule's table name
func (*ChristmasNewUserSupportRule) TableName() string {
	return TableNameChristmasNewUserSupportRule
}
