// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGamePagcor = "game_pagcor"

// GamePagcor pagcor游戏分类列表
type GamePagcor struct {
	ID        int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:类型:1-e-game 2-e-bingo 3-sport 4-arcodes" json:"id"` // 类型:1-e-game 2-e-bingo 3-sport 4-arcodes
	Name      string  `gorm:"column:name;not null;comment:自定类型名称" json:"name"`                                                   // 自定类型名称
	Icon      string  `gorm:"column:icon" json:"icon"`
	Status    int32   `gorm:"column:status;not null;comment:状态: 1-启用 0-停用" json:"status"`           // 状态: 1-启用 0-停用
	TaxRate   float64 `gorm:"column:tax_rate;not null;default:0.0000;comment:监管税率" json:"tax_rate"` // 监管税率
	CreatedAt int32   `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt int32   `gorm:"column:updated_at;not null" json:"updated_at"`
	CreatedBy string  `gorm:"column:created_by;comment:操作人姓名" json:"created_by"` // 操作人姓名
	UpdatedBy string  `gorm:"column:updated_by;comment:最后更新人" json:"updated_by"` // 最后更新人
}

// TableName GamePagcor's table name
func (*GamePagcor) TableName() string {
	return TableNameGamePagcor
}
