// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinSetting = "win_settings"

// WinSetting 系统配置
type WinSetting struct {
	Code      string `gorm:"column:code;primaryKey;comment:code" json:"code"`     // code
	Value     string `gorm:"column:value;not null;comment:字符串或json" json:"value"` // 字符串或json
	CreatedAt int32  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt int32  `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName WinSetting's table name
func (*WinSetting) TableName() string {
	return TableNameWinSetting
}
