// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinUserFlag = "win_user_flag"

// WinUserFlag 会员旗表
type WinUserFlag struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	BitCode      int32  `gorm:"column:bit_code;comment:位运算占位符值" json:"bit_code"`   // 位运算占位符值
	Name         string `gorm:"column:name;comment:会员旗名称" json:"name"`             // 会员旗名称
	Icon         string `gorm:"column:icon;comment:图标" json:"icon"`                // 图标
	IconColor    string `gorm:"column:icon_color;comment:图标颜色" json:"icon_color"`  // 图标颜色
	Status       int32  `gorm:"column:status;comment:状态: 1-启用 0-禁用" json:"status"` // 状态: 1-启用 0-禁用
	CreatedAt    int32  `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    int32  `gorm:"column:updated_at" json:"updated_at"`
	OperatorName string `gorm:"column:operator_name;comment:操作人姓名" json:"operator_name"` // 操作人姓名
}

// TableName WinUserFlag's table name
func (*WinUserFlag) TableName() string {
	return TableNameWinUserFlag
}
