// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinMonthlyTax = "win_monthly_tax"

// WinMonthlyTax 每月税收统计
type WinMonthlyTax struct {
	ID         int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	GameID     int32   `gorm:"column:game_id;not null;comment:游戏ID" json:"game_id"`          // 游戏ID
	GameName   string  `gorm:"column:game_name;not null;comment:游戏名称" json:"game_name"`      // 游戏名称
	Year       int32   `gorm:"column:year;not null;comment:统计年" json:"year"`                 // 统计年
	Month      int32   `gorm:"column:month;not null;comment:统计月" json:"month"`               // 统计月
	CoinBet    float64 `gorm:"column:coin_bet;not null;comment:投注金额" json:"coin_bet"`        // 投注金额
	CoinProfit float64 `gorm:"column:coin_profit;not null;comment:负盈利金额" json:"coin_profit"` // 负盈利金额
	Rate       float64 `gorm:"column:rate;not null;comment:税收比例" json:"rate"`                // 税收比例
	CoinTax    float64 `gorm:"column:coin_tax;not null;comment:税收金额" json:"coin_tax"`        // 税收金额
	CreatedAt  int32   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`    // 创建时间
	UpdatedAt  int32   `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`    // 修改时间
}

// TableName WinMonthlyTax's table name
func (*WinMonthlyTax) TableName() string {
	return TableNameWinMonthlyTax
}
