// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinUserPromotionRegistration = "win_user_promotion_registration"

// WinUserPromotionRegistration 用户推广注册信息表
type WinUserPromotionRegistration struct {
	ID               int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                           // 主键
	ImportTime       int64   `gorm:"column:import_time;not null;comment:导入时间" json:"import_time"`                            // 导入时间
	BatchNumber      int64   `gorm:"column:batch_number;not null;comment:批次号" json:"batch_number"`                           // 批次号
	PhoneNumber      int64   `gorm:"column:phone_number;not null;comment:手机号" json:"phone_number"`                           // 手机号
	RegistrationTime int64   `gorm:"column:registration_time;not null;comment:注册时间" json:"registration_time"`                // 注册时间
	UserID           int32   `gorm:"column:user_id;not null;comment:注册用户id" json:"user_id"`                                  // 注册用户id
	OpUser           string  `gorm:"column:op_user;not null;default:system;comment:操作人" json:"op_user"`                      // 操作人
	CreatedAt        int64   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                              // 创建时间
	UpdatedAt        int64   `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                              // 更新时间
	PayAmount        float64 `gorm:"column:pay_amount;not null;default:0.0000;comment:充值金额" json:"pay_amount"`               // 充值金额
	WithdrawalAmount float64 `gorm:"column:withdrawal_amount;not null;default:0.0000;comment:提款金额" json:"withdrawal_amount"` // 提款金额
	DiffAmount       float64 `gorm:"column:diff_amount;not null;default:0.0000;comment:存提差额" json:"diff_amount"`             // 存提差额
	EffectedAt       int64   `gorm:"column:effected_at;not null;comment:导入生效时间" json:"effected_at"`                          // 导入生效时间
}

// TableName WinUserPromotionRegistration's table name
func (*WinUserPromotionRegistration) TableName() string {
	return TableNameWinUserPromotionRegistration
}
