// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinUserOnlineReport = "win_user_online_report"

// WinUserOnlineReport 在线会员人数报表
type WinUserOnlineReport struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`       // 自增主键
	StartTime   int32  `gorm:"column:start_time;not null;comment:统计开始时间" json:"start_time"`          // 统计开始时间
	EndTime     int32  `gorm:"column:end_time;not null;comment:统计结束时间" json:"end_time"`              // 统计结束时间
	Category    int32  `gorm:"column:category;not null;comment:统计类型：0-时报，1-日报，2-月报" json:"category"` // 统计类型：0-时报，1-日报，2-月报
	OnlineAvg   int32  `gorm:"column:online_avg;not null;comment:平均在线人数" json:"online_avg"`          // 平均在线人数
	OnlineMax   int32  `gorm:"column:online_max;not null;comment:最高在线人数" json:"online_max"`          // 最高在线人数
	OnlineMin   int32  `gorm:"column:online_min;not null;comment:最低在线人数" json:"online_min"`          // 最低在线人数
	CreatedAt   int32  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`            // 创建时间
	UpdatedAt   int32  `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`            // 修改时间
	UpdatedUser string `gorm:"column:updated_user;comment:最后修改人" json:"updated_user"`                // 最后修改人
}

// TableName WinUserOnlineReport's table name
func (*WinUserOnlineReport) TableName() string {
	return TableNameWinUserOnlineReport
}
