// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinUserFbMarket = "win_user_fb_market"

// WinUserFbMarket FB营销表
type WinUserFbMarket struct {
	ID          int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`     // 自增主键
	UID         int32   `gorm:"column:uid;not null;comment:UID" json:"uid"`                         // UID
	Amount      float64 `gorm:"column:amount;not null;default:0.0000;comment:赠送金额" json:"amount"`   // 赠送金额
	KycFlag     int32   `gorm:"column:kyc_flag;not null;comment:是否需要完成kyc:0-否，1-是" json:"kyc_flag"` // 是否需要完成kyc:0-否，1-是
	Remark      string  `gorm:"column:remark;not null;comment:备注" json:"remark"`                    // 备注
	CreatedAt   int32   `gorm:"column:created_at;not null;comment:赠送时间" json:"created_at"`          // 赠送时间
	UpdatedAt   int32   `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`          // 修改时间
	UpdatedUser string  `gorm:"column:updated_user;comment:最后修改人" json:"updated_user"`              // 最后修改人
}

// TableName WinUserFbMarket's table name
func (*WinUserFbMarket) TableName() string {
	return TableNameWinUserFbMarket
}
