// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinCodeRecord = "win_code_records"

// WinCodeRecord 打码量记录表
type WinCodeRecord struct {
	ID                int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID               int32   `gorm:"column:uid;not null;comment:UID" json:"uid"`                                                           // UID
	Username          string  `gorm:"column:username;not null;comment:用户名" json:"username"`                                                 // 用户名
	Coin              float64 `gorm:"column:coin;not null;comment:金额" json:"coin"`                                                          // 金额
	CodeRequire       float64 `gorm:"column:code_require;not null;comment:需求打码量" json:"code_require"`                                       // 需求打码量
	FlowClaim         float64 `gorm:"column:flow_claim;comment:需求打码倍数" json:"flow_claim"`                                                   // 需求打码倍数
	RealCode          float64 `gorm:"column:real_code;comment:实际打码量" json:"real_code"`                                                      // 实际打码量
	VipRealCode       float64 `gorm:"column:vip_real_code;comment:vip打码量" json:"vip_real_code"`                                             // vip打码量
	Category          int32   `gorm:"column:category;not null;comment:类型:1-充值 2-签到活动 3- 系统调账 4注册活动 5-特定活动,6-救济金活动，7-充值送活动" json:"category"` // 类型:1-充值 2-签到活动 3- 系统调账 4注册活动 5-特定活动,6-救济金活动，7-充值送活动
	ReferID           int64   `gorm:"column:refer_id;not null;comment:关联ID" json:"refer_id"`                                                // 关联ID
	ReferWithdrawalID int64   `gorm:"column:refer_withdrawal_id;comment:关联提款ID" json:"refer_withdrawal_id"`                                 // 关联提款ID
	Remarks           string  `gorm:"column:remarks;not null;comment:备注" json:"remarks"`                                                    // 备注
	Status            int32   `gorm:"column:status;not null;comment:状态:0-未结算 1-结算" json:"status"`                                           // 状态:0-未结算 1-结算
	CreatedAt         int32   `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt         int32   `gorm:"column:updated_at;not null" json:"updated_at"`
	ActivityID        int64   `gorm:"column:activity_id;not null;comment:活动ID" json:"activity_id"`            // 活动ID
	OpUser            string  `gorm:"column:op_user;not null;default:system;comment:操作人" json:"op_user"`      // 操作人
	Flag              int32   `gorm:"column:flag;not null;comment:是否需要修改标记：0-正常，1-大于，2-小于，3-等于" json:"flag"`  // 是否需要修改标记：0-正常，1-大于，2-小于，3-等于
	IsAudit           int32   `gorm:"column:is_audit;not null;comment:是否被強制稽核過:0否 1是" json:"is_audit"`        // 是否被強制稽核過:0否 1是
	BindingID         int64   `gorm:"column:binding_id;not null;comment:充值活動碼量與彩金活動碼量綁定Id" json:"binding_id"` // 充值活動碼量與彩金活動碼量綁定Id
}

// TableName WinCodeRecord's table name
func (*WinCodeRecord) TableName() string {
	return TableNameWinCodeRecord
}
