// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinUserGoogleCode = "win_user_google_code"

// WinUserGoogleCode 会员谷歌验证码
type WinUserGoogleCode struct {
	UID        int32  `gorm:"column:uid;primaryKey;comment:用户id" json:"uid"`                       // 用户id
	GoogleCode string `gorm:"column:google_code;not null;comment:谷歌令牌" json:"google_code"`         // 谷歌令牌
	Status     int32  `gorm:"column:status;not null;default:1;comment:状态:1-开启 0-禁用" json:"status"` // 状态:1-开启 0-禁用
	CreatedAt  int32  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt  int32  `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName WinUserGoogleCode's table name
func (*WinUserGoogleCode) TableName() string {
	return TableNameWinUserGoogleCode
}
