// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinCodeRecordsVip = "win_code_records_vip"

// WinCodeRecordsVip VIP会员有效流水表
type WinCodeRecordsVip struct {
	ID              int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"`                     // 自增主键
	Remark          string  `gorm:"column:remark;not null;comment:备注" json:"remark"`                                    // 备注
	UID             int32   `gorm:"column:uid;not null;comment:UID" json:"uid"`                                         // UID
	ValidAmount     float64 `gorm:"column:valid_amount;not null;default:0.0000;comment:有效投注额/赠送金额" json:"valid_amount"` // 有效投注额/赠送金额
	Category        int32   `gorm:"column:category;not null;default:1;comment:类型:1-有效投注额 2-赠送金额" json:"category"`       // 类型:1-有效投注额 2-赠送金额
	Version         int32   `gorm:"column:version;not null;comment:更新版本号" json:"version"`                               // 更新版本号
	CreatedAt       int32   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                          // 创建时间
	UpdatedAt       int32   `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`                          // 修改时间
	UpdatedUser     string  `gorm:"column:updated_user;comment:最后修改人" json:"updated_user"`                              // 最后修改人
	DaysNotLogin    int32   `gorm:"column:days_not_login;not null;comment:未上线天数" json:"days_not_login"`                 // 未上线天数
	AlreadySmsCount int32   `gorm:"column:already_sms_count;not null;comment:已发送消息条数" json:"already_sms_count"`         // 已发送消息条数
}

// TableName WinCodeRecordsVip's table name
func (*WinCodeRecordsVip) TableName() string {
	return TableNameWinCodeRecordsVip
}
