// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinCodeAudit = "win_code_audit"

// WinCodeAudit mapped from table <win_code_audit>
type WinCodeAudit struct {
	ID            int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`     // ID
	UID           int32   `gorm:"column:uid;not null;comment:uid" json:"uid"`                       // uid
	Username      string  `gorm:"column:username;not null;comment:用户名" json:"username"`             // 用户名
	AuditUsername string  `gorm:"column:audit_username;not null;comment:审核人" json:"audit_username"` // 审核人
	CodeRequire   float64 `gorm:"column:code_require;not null;comment:所需打码量" json:"code_require"`   // 所需打码量
	CodeReal      float64 `gorm:"column:code_real;not null;comment:真实打码量" json:"code_real"`         // 真实打码量
	ReferID       int64   `gorm:"column:refer_id;not null;comment:对应的提款订单ID" json:"refer_id"`       // 对应的提款订单ID
	Status        int32   `gorm:"column:status;not null;comment:状态:1-稽核成功 2-稽核失败" json:"status"`    // 状态:1-稽核成功 2-稽核失败
	CreatedAt     int32   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`        // 创建时间
	UpdatedAt     int32   `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName WinCodeAudit's table name
func (*WinCodeAudit) TableName() string {
	return TableNameWinCodeAudit
}
