// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinAdminExportFileTask = "win_admin_export_file_task"

// WinAdminExportFileTask 导出文件任务表
type WinAdminExportFileTask struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                    // id
	TaskName     string `gorm:"column:task_name;not null;comment:导出任务名" json:"task_name"`                        // 导出任务名
	TaskParam    string `gorm:"column:task_param;not null;comment:导出查询参数" json:"task_param"`                     // 导出查询参数
	StatusCode   int32  `gorm:"column:status_code;not null;comment:导出状态码，2=处理中，3=文件已生成，5=失败" json:"status_code"` // 导出状态码，2=处理中，3=文件已生成，5=失败
	StatusMess   string `gorm:"column:status_mess;not null;comment:导出状态信息" json:"status_mess"`                   // 导出状态信息
	FilePath     string `gorm:"column:file_path;not null;comment:文件路径" json:"file_path"`                         // 文件路径
	FilePathHash int32  `gorm:"column:file_path_hash;not null;comment:文件路径hash" json:"file_path_hash"`           // 文件路径hash
	OperatorID   int32  `gorm:"column:operator_id;not null;comment:操作人id" json:"operator_id"`                    // 操作人id
	CreatedAt    int32  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                       // 创建时间
	UpdatedAt    int32  `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                       // 更新时间
}

// TableName WinAdminExportFileTask's table name
func (*WinAdminExportFileTask) TableName() string {
	return TableNameWinAdminExportFileTask
}
