// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinCoinLog = "win_coin_log"

type WinCoinLog struct {
	ID         int64   `gorm:"column:id;primaryKey" json:"id"`
	UID        int32   `gorm:"column:uid;not null;comment:UID" json:"uid"`                                                                                                                               // UID
	Username   string  `gorm:"column:username;not null;comment:用户名" json:"username"`                                                                                                                  // 用户名
	MerchantID int32   `gorm:"column:merchant_id;not null;comment:商户id" json:"merchant_id"`                                                                                                            // 商户id
	WalletID   int32   `gorm:"column:wallet_id;not null;comment:钱包id" json:"wallet_id"`                                                                                                                // 钱包id
	Currency   int32   `gorm:"column:currency;not null;default:1;comment:币种" json:"currency"`                                                                                                          // 币种
	Category   int32   `gorm:"column:category;not null;default:1;comment:类型:1-存款 2-提款 3-投注 4-派彩 5-返水 6-佣金 7-活动(奖励) 8-系统调账 9-退款 10-佣金钱包转主账户余额 11-小费" json:"category"` // 类型:1-存款 2-提款 3-投注 4-派彩 5-返水 6-佣金 7-活动(奖励) 8-系统调账 9-退款 10-佣金钱包转主账户余额 11-小费
	ReferID    int64   `gorm:"column:refer_id;comment:关联ID" json:"refer_id"`                                                                                                                           // 关联ID
	Coin       float64 `gorm:"column:coin;not null;default:0.0000;comment:金额" json:"coin"`                                                                                                             // 金额
	CoinReal   float64 `gorm:"column:coin_real;not null;default:0.0000;comment:实际金额" json:"coin_real"`                                                                                               // 实际金额
	PlatID     int32   `gorm:"column:plat_id;not null;comment:游戏平台ID" json:"plat_id"`                                                                                                                // 游戏平台ID
	OutIn      int32   `gorm:"column:out_in;not null;comment:收支类型:0-支出 1-收入" json:"out_in"`                                                                                                      // 收支类型:0-支出 1-收入
	GameID     int32   `gorm:"column:game_id;not null;comment:三方游戏ID" json:"game_id"`                                                                                                                // 三方游戏ID
	CoinBefore float64 `gorm:"column:coin_before;not null;default:0.0000;comment:前金额" json:"coin_before"`                                                                                             // 前金额
	CoinAfter  float64 `gorm:"column:coin_after;not null;default:0.0000;comment:帐变后金额" json:"coin_after"`                                                                                           // 帐变后金额
	Status     int32   `gorm:"column:status;not null;comment:状态:0-处理中 1-成功 2-失败" json:"status"`                                                                                                 // 状态:0-处理中 1-成功 2-失败
	CreatedAt  int32   `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt  int32   `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName WinCoinLog0's table name
func (m *WinCoinLog) TableName() string {
	return TableNameWinCoinLog
}
