// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinUserExt = "win_user_ext"

// WinUserExt 用户扩展信息
type WinUserExt struct {
	ID                     int32   `gorm:"column:id;primaryKey;comment:用户ID" json:"id"`                                                                 // 用户ID
	Username               string  `gorm:"column:username;not null;comment:用户名" json:"username"`                                                        // 用户名
	AgentLevel             int32   `gorm:"column:agent_level;not null;comment:代理等级" json:"agent_level"`                                                 // 代理等级
	AgentPath              string  `gorm:"column:agent_path;comment:代理详细路径-分割" json:"agent_path"`                                                       // 代理详细路径-分割
	TeamCount              int32   `gorm:"column:team_count;not null;comment:团队总人数" json:"team_count"`                                                  // 团队总人数
	TeamDirectCount        int32   `gorm:"column:team_direct_count;not null;comment:团队直属人" json:"team_direct_count"`                                    // 团队直属人
	LevelID                int32   `gorm:"column:level_id;not null;default:1;comment:会员等级" json:"level_id"`                                             // 会员等级
	LevelMax               int32   `gorm:"column:level_max;not null;default:1;comment:用户达到最高等级" json:"level_max"`                                       // 用户达到最高等级
	LevelBet               float64 `gorm:"column:level_bet;not null;default:0.0000;comment:vip等级投注总额" json:"level_bet"`                                 // vip等级投注总额
	LevelDeposit           float64 `gorm:"column:level_deposit;not null;default:0.0000;comment:vip等级充值总额" json:"level_deposit"`                         // vip等级充值总额
	LevelChangeAt          int32   `gorm:"column:level_change_at;comment:等级变更时间" json:"level_change_at"`                                                // 等级变更时间
	TotalDeposit           float64 `gorm:"column:total_deposit;not null;default:0.0000;comment:充值总额" json:"total_deposit"`                              // 充值总额
	TotalAdminTransfer     float64 `gorm:"column:total_admin_transfer;not null;default:0.0000;comment:调账总额绝对值" json:"total_admin_transfer"`             // 调账总额绝对值
	TotalAdminTransferSub  float64 `gorm:"column:total_admin_transfer_sub;not null;default:0.0000;comment:调账总额减" json:"total_admin_transfer_sub"`       // 调账总额减
	TotalAdminTransferAdd  float64 `gorm:"column:total_admin_transfer_add;not null;default:0.0000;comment:调账总额加" json:"total_admin_transfer_add"`       // 调账总额加
	TotalBet               float64 `gorm:"column:total_bet;not null;default:0.0000;comment:投注总额" json:"total_bet"`                                      // 投注总额
	TotalValidBet          float64 `gorm:"column:total_valid_bet;not null;default:0.0000;comment:有效投注总额" json:"total_valid_bet"`                        // 有效投注总额
	TotalWithdrawal        float64 `gorm:"column:total_withdrawal;not null;default:0.0000;comment:提款总额" json:"total_withdrawal"`                        // 提款总额
	WithdrawalNum          int32   `gorm:"column:withdrawal_num;not null;comment:提款次数" json:"withdrawal_num"`                                           // 提款次数
	DepositNum             int32   `gorm:"column:deposit_num;not null;comment:充值次数" json:"deposit_num"`                                                 // 充值次数
	WithdrawalMustCode     float64 `gorm:"column:withdrawal_must_code;not null;default:0.0000;comment:下次提现所需打码量" json:"withdrawal_must_code"`           // 下次提现所需打码量
	WithdrawalMustRealCode float64 `gorm:"column:withdrawal_must_real_code;not null;default:0.0000;comment:下次提现实际打码量" json:"withdrawal_must_real_code"` // 下次提现实际打码量
	CreatedAt              int32   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                                                   // 创建时间
	UpdatedAt              int32   `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`                                                   // 修改时间
}

// TableName WinUserExt's table name
func (*WinUserExt) TableName() string {
	return TableNameWinUserExt
}
