// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinAdminOperateLog = "win_admin_operate_log"

// WinAdminOperateLog 管理员操作日志表
type WinAdminOperateLog struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID       int32  `gorm:"column:uid;not null;comment:UID" json:"uid"`           // UID
	Username  string `gorm:"column:username;not null;comment:用户名" json:"username"` // 用户名
	Title     string `gorm:"column:title;not null;comment:标题" json:"title"`        // 标题
	URL       string `gorm:"column:url;not null;comment:请求url" json:"url"`         // 请求url
	ReqParams string `gorm:"column:req_params;comment:请求参数" json:"req_params"`     // 请求参数
	ResParams string `gorm:"column:res_params;comment:响应参数" json:"res_params"`     // 响应参数
	IP        string `gorm:"column:ip;not null" json:"ip"`
	CreatedAt int32  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt int32  `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName WinAdminOperateLog's table name
func (*WinAdminOperateLog) TableName() string {
	return TableNameWinAdminOperateLog
}
