// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinCoinRebate = "win_coin_rebate"

// WinCoinRebate 返水
type WinCoinRebate struct {
	ID           int64   `gorm:"column:id;primaryKey" json:"id"`
	UID          int32   `gorm:"column:uid;not null;comment:UID" json:"uid"`                            // UID
	Username     string  `gorm:"column:username;not null;comment:用户名" json:"username"`                  // 用户名
	LevelID      int32   `gorm:"column:level_id;not null;comment:会员等级" json:"level_id"`                 // 会员等级
	SettleDate   string  `gorm:"column:settle_date;not null;comment:结算日期" json:"settle_date"`           // 结算日期
	VaildStake   float64 `gorm:"column:vaild_stake;not null;comment:有效投注额" json:"vaild_stake"`          // 有效投注额
	GroupID      int32   `gorm:"column:group_id;not null;comment:游戏类型" json:"group_id"`                 // 游戏类型
	RebateRate   float64 `gorm:"column:rebate_rate;not null;comment:返水比例" json:"rebate_rate"`           // 返水比例
	RabateCoin   float64 `gorm:"column:rabate_coin;not null;comment:返水金额" json:"rabate_coin"`           // 返水金额
	Status       int32   `gorm:"column:status;not null;default:1;comment:状态:1-已发放 0-未发放" json:"status"` // 状态:1-已发放 0-未发放
	CreatedAt    int32   `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt    int32   `gorm:"column:updated_at;not null" json:"updated_at"`
	ExpiredAt    int32   `gorm:"column:expired_at;not null;comment:返水过期时间" json:"expired_at"`       // 返水过期时间
	EffectivedAt int32   `gorm:"column:effectived_at;not null;comment:返水生效时间" json:"effectived_at"` // 返水生效时间
}

// TableName WinCoinRebate's table name
func (*WinCoinRebate) TableName() string {
	return TableNameWinCoinRebate
}
