// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinCoinRate = "win_coin_rate"

// WinCoinRate 汇率表
type WinCoinRate struct {
	ID               int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`            // ID
	OriginalCurrency string  `gorm:"column:original_currency;not null;comment:原始币种" json:"original_currency"` // 原始币种
	TransferCurrency string  `gorm:"column:transfer_currency;not null;comment:转换币种" json:"transfer_currency"` // 转换币种
	Rate             float64 `gorm:"column:rate;not null;default:0.00000000;comment:汇率" json:"rate"`          // 汇率
	Status           int32   `gorm:"column:status;not null;default:1;comment:状态：0-关闭；1-开启" json:"status"`     // 状态：0-关闭；1-开启
	CreatedAt        int32   `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`               // 创建时间
	UpdatedAt        int32   `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`               // 修改时间
	OperatorName     string  `gorm:"column:operator_name;comment:操作人姓名" json:"operator_name"`                 // 操作人姓名
}

// TableName WinCoinRate's table name
func (*WinCoinRate) TableName() string {
	return TableNameWinCoinRate
}
