// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinUserFacebookLogin = "win_user_facebook_login"

// WinUserFacebookLogin 客户Facebook登陆关联表
type WinUserFacebookLogin struct {
	ID             int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                  // 主键
	UserID         int32  `gorm:"column:user_id;not null;comment:客户表ID" json:"user_id"`                          // 客户表ID
	Username       string `gorm:"column:username;not null;comment:用户名" json:"username"`                          // 用户名
	FacebookUserID string `gorm:"column:facebook_user_id;not null;comment:Facebook用户ID" json:"facebook_user_id"` // Facebook用户ID
	CreatedAt      int32  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                     // 创建时间
}

// TableName WinUserFacebookLogin's table name
func (*WinUserFacebookLogin) TableName() string {
	return TableNameWinUserFacebookLogin
}
