// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinUserGoogleLogin = "win_user_google_login"

// WinUserGoogleLogin 客户谷歌登陆关联表
type WinUserGoogleLogin struct {
	ID               int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                // 主键
	UserID           int32  `gorm:"column:user_id;not null;comment:客户表ID" json:"user_id"`                        // 客户表ID
	Username         string `gorm:"column:username;not null;comment:用户名" json:"username"`                        // 用户名
	GoogleLoginEmail string `gorm:"column:google_login_email;not null;comment:谷歌登陆邮箱" json:"google_login_email"` // 谷歌登陆邮箱
	CreatedAt        int32  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                   // 创建时间
}

// TableName WinUserGoogleLogin's table name
func (*WinUserGoogleLogin) TableName() string {
	return TableNameWinUserGoogleLogin
}
