// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinUserOnline = "win_user_online"

// WinUserOnline 每分钟在线会员人数表
type WinUserOnline struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增主键" json:"id"` // 自增主键
	TimeSum     int32  `gorm:"column:time_sum;not null;comment:统计时间" json:"time_sum"`          // 统计时间
	OnlineSum   int32  `gorm:"column:online_sum;not null;comment:在线人数" json:"online_sum"`      // 在线人数
	CreatedAt   int32  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`      // 创建时间
	UpdatedAt   int32  `gorm:"column:updated_at;not null;comment:修改时间" json:"updated_at"`      // 修改时间
	UpdatedUser string `gorm:"column:updated_user;comment:最后修改人" json:"updated_user"`          // 最后修改人
}

// TableName WinUserOnline's table name
func (*WinUserOnline) TableName() string {
	return TableNameWinUserOnline
}
