// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinFrontGameBigCategoryBanner = "win_front_game_big_category_banner"

// WinFrontGameBigCategoryBanner 游戏大类BANNER表
type WinFrontGameBigCategoryBanner struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string `gorm:"column:name;not null;comment:名称" json:"name"`                       // 名称
	PcImg       string `gorm:"column:pc_img;not null;comment:pc图片地址" json:"pc_img"`               // pc图片地址
	H5Img       string `gorm:"column:h5_img;not null;comment:h5图片地址" json:"h5_img"`               // h5图片地址
	GameGroupID int32  `gorm:"column:game_group_id;not null;comment:游戏大类id" json:"game_group_id"` // 游戏大类id
	Sort        int32  `gorm:"column:sort;default:100;comment:排序字段" json:"sort"`                  // 排序字段
	Status      int32  `gorm:"column:status;not null;comment:状态:1-启用 0-停用" json:"status"`         // 状态:1-启用 0-停用
	CreatedAt   int32  `gorm:"column:created_at;not null" json:"created_at"`
	CreatedBy   string `gorm:"column:created_by;not null;comment:创建者" json:"created_by"` // 创建者
	UpdatedAt   int32  `gorm:"column:updated_at;not null" json:"updated_at"`
	UpdatedBy   string `gorm:"column:updated_by;not null;comment:更新人" json:"updated_by"` // 更新人
}

// TableName WinFrontGameBigCategoryBanner's table name
func (*WinFrontGameBigCategoryBanner) TableName() string {
	return TableNameWinFrontGameBigCategoryBanner
}
