// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinFbOrderLog = "win_fb_order_log"

// WinFbOrderLog Fb体育订单流水表
type WinFbOrderLog struct {
	ID              int64   `gorm:"column:id;primaryKey" json:"id"`
	TransactionID   string  `gorm:"column:transaction_id;comment:交易流水ID，全服唯一" json:"transaction_id"`           // 交易流水ID，全服唯一
	UserID          string  `gorm:"column:user_id;comment:FB用户ID" json:"user_id"`                              // FB用户ID
	MerchantID      string  `gorm:"column:merchant_id;comment:渠道ID" json:"merchant_id"`                        // 渠道ID
	MerchantUserID  string  `gorm:"column:merchant_user_id;comment:渠道用户ID" json:"merchant_user_id"`            // 渠道用户ID
	BusinessID      string  `gorm:"column:business_id;comment:业务ID，即订单ID" json:"business_id"`                  // 业务ID，即订单ID
	TransactionType string  `gorm:"column:transaction_type;comment:交易类型 OUT 转出，IN 转入" json:"transaction_type"` // 交易类型 OUT 转出，IN 转入
	TransferType    string  `gorm:"column:transfer_type;comment:转账类型" json:"transfer_type"`                    // 转账类型
	CurrencyID      int32   `gorm:"column:currency_id;comment:币种ID" json:"currency_id"`                        // 币种ID
	Amount          float64 `gorm:"column:amount;comment:流水金额" json:"amount"`                                  // 流水金额
	Status          int32   `gorm:"column:status;comment:转账状态,0 取消，1成功" json:"status"`                         // 转账状态,0 取消，1成功
	RelatedID       string  `gorm:"column:related_id;comment:三方数据关联ID" json:"related_id"`                      // 三方数据关联ID
	CreatedAt       int32   `gorm:"column:created_at;comment:创建时间" json:"created_at"`                          // 创建时间
}

// TableName WinFbOrderLog's table name
func (*WinFbOrderLog) TableName() string {
	return TableNameWinFbOrderLog
}
