// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinBetslipsDetails = "win_betslips_details"

// WinBetslipsDetails mapped from table <win_betslips_details_0>
type WinBetslipsDetails struct {
	ID         int64  `gorm:"column:id;primaryKey;comment:主键-同注单表一致" json:"id"`                  // 主键-同注单表一致
	XbUID      int32  `gorm:"column:xb_uid;not null;comment:对应user表id" json:"xb_uid"`                 // 对应user表id
	XbUsername string `gorm:"column:xb_username;not null;comment:对应user表username" json:"xb_username"` // 对应user表username
	BetJSON    string `gorm:"column:bet_json;comment:投注原始json" json:"bet_json"`                      // 投注原始json
	RewardJSON string `gorm:"column:reward_json;comment:开彩原始json" json:"reward_json"`                // 开彩原始json
	RefundJSON string `gorm:"column:refund_json;comment:退款原始json" json:"refund_json"`                // 退款原始json
}

func (m *WinBetslipsDetails) TableName() string {
	return TableNameWinBetslipsDetails
}
