// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWinUserLoginLog = "win_user_login_log"

// WinUserLoginLog 用户日志表
type WinUserLoginLog struct {
	ID          int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID         int32   `gorm:"column:uid;not null;comment:UID" json:"uid"`                            // UID
	Username    string  `gorm:"column:username;not null;comment:用户名" json:"username"`                  // 用户名
	MerchantID  int32   `gorm:"column:merchant_id;not null;comment:商户id" json:"merchant_id"`           // 商户id
	Coin        float64 `gorm:"column:coin;default:0.0000;comment:账户余额" json:"coin"`                   // 账户余额
	IP          string  `gorm:"column:ip;comment:IP地址" json:"ip"`                                      // IP地址
	GameName    string  `gorm:"column:game_name;comment:游戏名称" json:"game_name"`                        // 游戏名称
	URL         string  `gorm:"column:url;comment:登录链接" json:"url"`                                    // 登录链接
	Device      string  `gorm:"column:device;comment:设备:m-手机 d-电脑 ANDROID-安卓 IOS-苹果" json:"device"`    // 设备:m-手机 d-电脑 ANDROID-安卓 IOS-苹果
	Category    int32   `gorm:"column:category;default:1;comment:类型:0-登出 1-登录 2-进入游戏" json:"category"` // 类型:0-登出 1-登录 2-进入游戏
	DeviceID    string  `gorm:"column:device_id;comment:设备id" json:"device_id"`                        // 设备id
	IsNewDevice int32   `gorm:"column:is_new_device;comment:是新设备id 0-不是 1-是" json:"is_new_device"`     // 是新设备id 0-不是 1-是
	Remark      string  `gorm:"column:remark;comment:备注" json:"remark"`                                // 备注
	CreatedAt   int32   `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   int32   `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName WinUserLoginLog's table name
func (*WinUserLoginLog) TableName() string {
	return TableNameWinUserLoginLog
}
