// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameXxlJobRegistry = "xxl_job_registry"

// XxlJobRegistry mapped from table <xxl_job_registry>
type XxlJobRegistry struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RegistryGroup string    `gorm:"column:registry_group;not null" json:"registry_group"`
	RegistryKey   string    `gorm:"column:registry_key;not null" json:"registry_key"`
	RegistryValue string    `gorm:"column:registry_value;not null" json:"registry_value"`
	UpdateTime    time.Time `gorm:"column:update_time" json:"update_time"`
}

// TableName XxlJobRegistry's table name
func (*XxlJobRegistry) TableName() string {
	return TableNameXxlJobRegistry
}
