// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameXxlJobLogglue = "xxl_job_logglue"

// XxlJobLogglue mapped from table <xxl_job_logglue>
type XxlJobLogglue struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	JobID      int32     `gorm:"column:job_id;not null;comment:任务，主键ID" json:"job_id"`          // 任务，主键ID
	GlueType   string    `gorm:"column:glue_type;comment:GLUE类型" json:"glue_type"`              // GLUE类型
	GlueSource string    `gorm:"column:glue_source;comment:GLUE源代码" json:"glue_source"`         // GLUE源代码
	GlueRemark string    `gorm:"column:glue_remark;not null;comment:GLUE备注" json:"glue_remark"` // GLUE备注
	AddTime    time.Time `gorm:"column:add_time" json:"add_time"`
	UpdateTime time.Time `gorm:"column:update_time" json:"update_time"`
}

// TableName XxlJobLogglue's table name
func (*XxlJobLogglue) TableName() string {
	return TableNameXxlJobLogglue
}
